---
linters:
  enable-all: true
  disable:
  - tagliatelle
  - interfacer # The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner
  - scopelint # The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref
  - maligned # The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'
  - wsl
  - goerr113
  - lll
  - godot
  - nlreturn
  - godox
  - golint
  - exhaustivestruct # https://github.com/mbilski/exhaustivestruct
