---
archives:
- name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
builds:
- binary: aws-iam-cred-sender
  id: aws-iam-cred-sender
  main: cmd/aws-iam-cred-sender/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
release:
  prerelease: true
